---
- name: Provision Data Science Toolbox
  hosts: default
  become: true

  tasks:
    - name: Install htop
      apt:
        pkg: htop

    - name: Install parallel
      apt:
        pkg: parallel

    - name: Install curl
      apt:
        pkg: curl

    - name: Install jq
      apt:
        pkg: jq

    - name: Install make
      apt:
        pkg: make

    - name: Install unzip
      apt:
        pkg: unzip

    - name: Install 7zip
      apt:
        pkg: p7zip-full

    - name: Install unrar
      apt:
        pkg: unrar-free

    - name: Install xmlstarlet
      apt:
        pkg: xmlstarlet

    - name: Install tree
      apt:
        pkg: tree

    - name: Install git
      package:
        name: git

    - name: Install cowsay
      apt:
        pkg: cowsay

    - name: Copy cowsay
      copy:
        remote_src: true
        src: /usr/games/cowsay
        dest: /usr/bin/cowsay
        mode: +x

    - name: Install xsv
      unarchive:
        src: https://github.com/BurntSushi/xsv/releases/download/0.13.0/xsv-0.13.0-x86_64-unknown-linux-musl.tar.gz
        dest: /usr/bin
        remote_src: true
        mode: +x

    - name: Install pup
      unarchive:
        src: https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip
        dest: /usr/bin
        remote_src: true
        mode: +x

    - name: Install requirements for vw
      apt:
        pkg:
          - libboost-dev
          - libboost-program-options-dev
          - libboost-system-dev
          - libboost-thread-dev
          - libboost-math-dev
          - libboost-test-dev
          - libboost-python-dev
          - zlib1g-dev
          - cmake
          - python3-pip

    - name: Install vw
      pip:
        name: vowpalwabbit

    - name: Create wheel group
      group:
        name: wheel
        state: present

    - name: Allow wheel group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

    - name: Prevent warning in sudo 1.8.31
      lineinfile:
        path: /etc/sudo.conf
        line: "Set disable_coredump false"
        create: yes

    - name: Create dst user
      user:
        name: dst
        password: "{{ 'dst' | password_hash('sha512') }}"
        shell: /bin/bash
        groups: wheel
        append: true
